version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - intranet_api_uploads:/uploads
    ports:
      - '8081:8081'

volumes:
  intranet_api_uploads:
