version: '3'
services:
  intranet_api:
    build: .
    ports:
      - '8081:8081'
    environment:
      PORT: 8081
      DATABASE_URL: postgresql://postgres:boss%3Fbossing%21@host.docker.internal:5432/db_intranet_test
    command: >
      sh -c "npm run start:prod"
