version: '3'
services:
  intranet_api:
    build: .
    ports:
      - '8081:8081'
    environment:
      # Use host.docker.internal or the host's IP
      DATABASE_URL: postgresql://postgres:boss%3Fbossing%21@10.255.255.254:5432/db_intranet_test
    command: >
      sh -c "npm run start:prod"
