version: '3'
services:
  intranet_api:
    build: .
    ports:
      - '8081:8081'
    environment:
      PORT: 8081
      DATABASE_URL: 'postgresql://postgres.nbbopzgdfempxvosydap:plzsupabasework@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true&connection_limit=1'
    command: >
      sh -c "npm run start:prod"
